#ifndef STAR_H
#define STAR_H

// Use this class to return stars from your find function.
// Use it to represent stars internally if you want.
// Do not edit this file.

struct Star {
    int   id = 0;
    float x = 0;
    float y = 0;
    float z = 0;
	Star() {};
	Star(float x, float y, float z):x(x),y(y),z(z){}
};

#endif
