#ifndef TRIP_H
#define TRIP_H

#include <string>
#include <vector>

// This is the structure used to return routes.
// Do not edit this file.

struct Trip {
  struct Leg {
    std::string line; // What transit line do you take?  你乘坐哪条公交线
    std::string stop; // What station do you get off at?  你在哪一站下车
  };

  std::string      start; // What station do you start at? 你从哪个车站出发
  std::vector<Leg> legs;  // Each leg of the trip, in order.  //行程的每一段，按顺序
};

#endif
